-- v3.46: a player keeps his salary for the whole season, even if he is waived.
--
-- Commissioner, 2026-09-26: "players keep their salary for the whole season even if they are waived."
--
-- ============================================================================
-- THE LINE THAT DID IT
-- ============================================================================
-- public.sign_free_agent ended its salary calculation with
--     v_salary := greatest(coalesce(p_salary, 750000), 750000);
--     if public.season_is_basic(v_season.id) then v_salary := 750000; end if;
-- so in the basic format EVERY signing of a waived player was forced to the league minimum,
-- whatever he had been earning. A club could waive a $3.25M player and any club, including the one
-- that waived him, could pick him up at $750,000. Being waived cost the player his salary and handed
-- the league a discount on him.
--
-- ============================================================================
-- WHAT IT READS NOW
-- ============================================================================
-- In the basic format the signing salary is the player's own, in this order:
--   1. his contract for this season. contract_on_waive sets status='expired' and team_id=null but
--      LEAVES THE SALARY on the row, so the figure survives the waiver untouched;
--   2. failing that, the salary recorded on his last archived roster spot (roster_spot_removals,
--      v3.17), which exists precisely so a removed spot remembers what it held;
--   3. failing both, the league minimum, as a FLOOR for a player with no salary on record.
-- Never as a reset. The full format is unchanged and still takes the offered salary.
--
-- apply_contract_on_roster needed nothing: after a waiver there is no ACTIVE contract, so it takes
-- its else branch and writes a new contract at the roster spot's salary, which is now the carried
-- figure. The cap is enforced where it always was, by guard_roster_cap on the insert, so a club that
-- cannot fit the real salary is refused rather than quietly given a discount.
--
-- ============================================================================
-- REHEARSED ON A REAL, EXPENSIVE PLAYER, ROLLED BACK
-- ============================================================================
-- The most expensive non-management active player in the league was waived by his own club and then
-- signed by a different club, in one rolled-back transaction. Three assertions:
--   * the new roster spot carries the SAME salary he was waived at
--   * the contract written for the new club carries it too
--   * and it is not 750000 unless that is genuinely what he earned
-- Nobody currently waived is affected: all six are at the league minimum already. This matters from
-- the first time a club waives somebody on a real salary, and Utah alone has a $3.25M and a $2.75M
-- player listed on the trade block tonight.
--
-- ============================================================================
-- THE READING I TOOK, SAID PLAINLY
-- ============================================================================
-- "Players keep their salary" is read as the PLAYER's salary following the PLAYER: he does not lose
-- it by being waived, and the club that signs him takes it on. The other possible reading, that the
-- WAIVING club keeps paying it as dead cap, is a different and much larger mechanic (the league has
-- salary_retention and apply_retention for the full format) and would have been described as such.
-- Rule 2.6 already uses the same words in the same sense for a manager who loses his seat: "A player
-- who earned a larger salary before taking the seat keeps that salary."
--
-- Rulebook: 2.2 (signing at the salary he was earning, with the cap consequence stated), 2.5 (a
-- depth placement carries the minimum; a waived player carries what he had). Rule 2.5 already said a
-- CLAIMING club "assumes the player at his pre-waiver salary, reinstated as it stood", so the basic
-- format was the odd one out and is now consistent with it.
--
-- ============================================================================
-- THE CLIENT HALF, WHICH ALMOST SHIPPED WRONG
-- ============================================================================
-- A background map of the salary surface caught what the database change alone would have left: the
-- page hardcoded the figure in four places and would have told a manager one number while charging
-- him another.
--   * the RPC call passed p_salary:750000 twice (the approval queue and the direct call). It now
--     passes NULL, so the database reads his contract and stays the single source of truth. A client
--     that names a salary is a client that can disagree with the rule.
--   * the confirmation dialog said "$750K to the end of the season". It now names his real salary,
--     says it is the salary he was already earning, and shows it against the club's remaining cap
--     space, so the cap hit is known BEFORE the button is pressed.
--   * the board lede and the one-button note both promised the league minimum. Rewritten.
--   * each waived player's row now carries his salary as a chip, because the figure travels with him
--     and a GM should not have to open a dialog to find out what a player costs.
-- CG.waivedSalaryOf mirrors the database read (his contract for this season, most recent first).
--
-- A NOTE ON THAT EDIT: the helper was first spliced in at the first textual match of
-- "CG.hubFreeAgents", which was the CALL inside CG.hubShell("freeagents", CG.hubFreeAgents()), not
-- the definition. That produced a file that parsed nowhere and a sandboxed rulebook test whose
-- catch(e){} swallowed the error and left CG undefined. `node --check` names the line in one second;
-- reach for it before reading a swallowed stack.
--
-- ============================================================================
-- FOUND WHILE MAPPING, NOT FIXED: Rule 2.5 describes a waiver system that does not exist
-- ============================================================================
-- Rule 2.5[3] still says "Waiving a player removes his cap hit from the club immediately and opens a
-- twenty-four (24) hour waiver period. A claiming club assumes the player at his pre-waiver salary".
-- There is no 24-hour window, no claim, and no claim RPC anywhere in sql/ or src/live/; Rule 2.2 says
-- the opposite, that he becomes a free agent at the moment he is waived and nothing happens
-- automatically. That paragraph is full-format machinery left in a basic-format book. It is a
-- rulebook cleanup, not a behaviour change, and is left for the commissioner to rule on.
